### ISSUE TITLE
Fix Icon Issues

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/contemplating-action#102]
## Description
Survey icon is missing and icon on individual info pages are too big

## Plan
- [x] Change font size for icons on info cards
- [x] Change the icon name for the survey

**Comment by jermyk** [comment]
- [x] Change font size for icons on info cards
- [x] Change the icon name for the survey 

![Screenshot_032519_014220_PM](https://user-images.githubusercontent.com/4446325/54924232-d5161080-4f03-11e9-87c7-3bba465b7d88.jpg)

**Comment by jermyk** [comment]
- [x] Change font size for icons on info cards
- [x] Change the icon name for the survey
