### ISSUE TITLE
Testing Issues

### ISSUE THREAD

**Issue by jermyk** [neontribe/contemplating-action#104]
## Description
What needs doing?

Issues and questions found during testing

## Plan
- [ ] Step one to achieve this.
- [ ] Step two to achieve this.

**Comment by jermyk** [comment]
https://neontribe.github.io/contemplating-action/#/stories/1

- [ ] Take part in our survey button doesn't fire

**Comment by katjam** [comment]
@HedgehogHolly You can card and try to fix the button... I've not checked into what is causing it but it might be possible for you to see. If not I'm happy to have a call and point you in the right direction. I suspect it's to do with the desktop vs mobile call to action where a phone number is not expected to have a link but a survey is.

**Comment by jermyk** [comment]
**Android styling**

Title needs some love
Page sits slightly right aligned.

![Screenshot_032519_044405_PM](https://user-images.githubusercontent.com/4446325/54937871-34cce580-4f1d-11e9-837e-06c549f01705.jpg)

**Comment by HedgehogHolly** [comment]
> **Android styling**
> 
> Title needs some love
> Page sits slightly right aligned.
> 
> ![Screenshot_032519_044405_PM](https://user-images.githubusercontent.com/4446325/54937871-34cce580-4f1d-11e9-837e-06c549f01705.jpg)

@jermyk Is this issue only on android? not other mobile views?

**Comment by jermyk** [comment]
@HedgehogHolly 
Only one found thus far. Might be worth waiting until I've done more testing before tidying up?

**Comment by jermyk** [comment]
https://github.com/neontribe/contemplating-action/issues/61

Link is not currently firing

**Comment by katjam** [comment]
Tasks were carded out.
