### ISSUE TITLE
Survey not firing on stories page

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/contemplating-action#105]
## Description
 Take part in our survey button doesn't fire on desktop

https://neontribe.github.io/contemplating-action/#/stories/1

## Acceptance Criteria
- [ ] Survey button under stories fires on desktop view
- [ ] Survey button under stories fires on mobile view
- [ ] Survey button on home page fires on desktop view
- [ ] Survey button on home page fires on mobile view
- [ ] Survey button in menu fires on desktop view
- [ ] Survey button in menu fires on mobile view

_Originally posted by @jermyk in https://github.com/neontribe/contemplating-action/issues/104#issuecomment-476222002_

**Comment by jermyk** [comment]
## Acceptance Criteria
- [x] Survey button under stories fires on desktop view
- [x] Survey button under stories fires on mobile view - **Tested on Android device & iPad**
- [x] Survey button on home page fires on desktop view
- [x] Survey button on home page fires on mobile view - **Tested on Android device & iPad**
- [x] Survey button in menu fires on desktop view
- [x] Survey button in menu fires on mobile view - **Tested on Android device & iPad**
