### ISSUE TITLE
Android styling

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/contemplating-action#106]
## Description
What needs doing?

Fix title leading on mobile view and the cutting of the nav 

## Plan
- [x] Fix line height issue
- [ ] Fix navigation issue (discuss change in copy)

![Screenshot_032519_044405_PM](https://user-images.githubusercontent.com/4446325/54937871-34cce580-4f1d-11e9-837e-06c549f01705.jpg)

_Originally posted by @jermyk in https://github.com/neontribe/contemplating-action/issues/104#issuecomment-476282663_

**Comment by jermyk** [comment]
@HedgehogHolly I'm still seeing the same gap in the header title as before?

**Comment by HedgehogHolly** [comment]
@jermyk what device are you using?

**Comment by katjam** [comment]
@jermyk maybe the fix hasn't been released to staging yet?

**Comment by katjam** [comment]
![Screenshot_20190503_143733](https://user-images.githubusercontent.com/861172/57140904-d06d3380-6db0-11e9-9c56-6568721c8577.png)
