### ISSUE TITLE
Copy: Landing Page

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#109]
## Insert word into tagline
Can visual stories help change lives

## Acceptance Criteria
- [x] Tag line on homepage reads: "A project exploring how to encourage people to seek support. Can visual stories help change lives?"

**Comment by HedgehogHolly** [comment]
@katjam @Nikomus now this copy is so short it looks a little odd, might be better centered?

![Screenshot 2019-03-29 at 11 47 20](https://user-images.githubusercontent.com/41140803/55230690-6e9d3500-5218-11e9-82ff-f4f2ab9d9489.png)

**Comment by katjam** [comment]
I don't want to change the design too much - charity versions might have longer text. @katquatermass what do you think?

**Comment by katjam** [comment]
https://user-images.githubusercontent.com/41140803/55230690-6e9d3500-5218-11e9-82ff-f4f2ab9d9489.png

@HedgehogHolly wondered if we should centre the short text.

**Comment by katjam** [comment]
@katquatermass Ignore us. I think we realised we want to keep the first sentence as well. See AC.

**Comment by jermyk** [comment]
## Acceptance Criteria
- [x] Tag line on homepage reads: "A project exploring how to encourage people to seek support. Can visual stories help change lives?"
![Screenshot_040219_104913_AM](https://user-images.githubusercontent.com/4446325/55393322-f47cf100-5534-11e9-9322-670ed5233dd3.jpg)
