### ISSUE TITLE
Incorporate elm-test & elm-format into project to avoid local version clashes

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#11]
## Description
We are running differing local versions of test and format

## Plan
- [x] Create yarn commands using local packages
- [x] Fix versions for `elm-format` and `elm-test`

## Acceptance Criteria
- [x] Devs on the project can format using same version of elm-format
- [x]  There is not requirement to install elm-format or elm-test globally
- [x] Devs can run tests
- [ ] Make an issue for the 'Todo's incorporate test into the CI/ build and incorporate format into the push.

**Comment by jermyk** [comment]
@katjam 

Looks like all the AC on this one are for Devs?

**Comment by katjam** [comment]
Thanks Karl. I'll flag it for @Nikomus or @HedgehogHolly to test since I coded it.

**Comment by Nikomus** [comment]
elm-format and elm-test are dependencies:
![image](https://user-images.githubusercontent.com/32434620/55168518-e2810400-516a-11e9-92c9-eaa89ddaf9a6.png)

Tests can be run..
![image](https://user-images.githubusercontent.com/32434620/55171665-b1a3cd80-5170-11e9-935f-815a45b5f495.png)

Plan item added to current CI ticket for running on build and push: https://github.com/neontribe/contemplating-action/issues/45
