### ISSUE TITLE
Copy Edit: about the project page

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#110]
## Change opening sentence to two sentences with slight word order edit.

In 2017, The Haven Wolverhampton worked with Neontribe and women who had been through domestic abuse. We co-designed a web app to encourage other women in that situation to seek support and advice.

## Acceptance Criteria
- [x] On the About the project page (info-to-help/about), the first 2 sentences are "In 2017, The Haven Wolverhampton, worked with Neontribe and women who had been through domestic abuse. We co-designed a web app to encourage other women in that situation to seek support and advice. "

**Comment by jermyk** [comment]
## Acceptance Criteria
- [x] On the About the project page (info-to-help/about), the first 2 sentences are "In 2017, The Haven Wolverhampton, worked with Neontribe and women who had been through domestic abuse. We co-designed a web app to encourage other women in that situation to seek support and advice. "
![Screenshot_040219_104508_AM](https://user-images.githubusercontent.com/4446325/55393046-61dc5200-5534-11e9-9d36-40387339d897.jpg)
