### ISSUE TITLE
Optional: Change illustrations to visual storytelling

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#111]
## Button name change to reflect project USP
Visual Storytelling (or Visual Stories if Storytelling is too long)
George points out that it would help if at least one of the buttons in the info section referred to the USP

## Plan
- [x] Because it is a button name, this might be too much code change for this stage - so make a decision if it is too big a change too late

## Acceptance Criteria

- [x] A button at the bottom of story 1 and 2 reads "Visual Storytelling"
- [x] On the info-to-help page, the button with pencil icon reads "Visual Storytelling"
- [x] clicking the Visual Storytelling button takes you to a page titled Visual Storytelling with a url slug of info-to-help/visual-storytelling

**Comment by jermyk** [comment]
## Acceptance Criteria

- [x] A button at the bottom of story 1 and 2 reads "Visual Storytelling"
![Screenshot_040219_103552_AM](https://user-images.githubusercontent.com/4446325/55392377-170e0a80-5533-11e9-93bd-2eaded34a346.jpg)

- [x] On the info-to-help page, the button with pencil icon reads "Visual Storytelling"
![Screenshot_040219_103829_AM](https://user-images.githubusercontent.com/4446325/55392549-753aed80-5533-11e9-8315-14d68b45c410.jpg)

- [x] clicking the Visual Storytelling button takes you to a page titled Visual Storytelling with a url slug of info-to-help/visual-storytelling
![Screenshot_040219_103957_AM](https://user-images.githubusercontent.com/4446325/55392659-a9161300-5533-11e9-8954-43e87381f361.jpg)
