### ISSUE TITLE
Copy edit: can my organisation try this

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#112]
## Change the opening sentences to:

We’re actively looking for partner charities interested in experimenting with this visual storytelling format. So if you have a helpline, webchat, messaging service or even a face to face service, we could work together on whether an app could help people connect to those services.

## Acceptance Criteria
- [ ] On the /info-to-help/try-this page, the opening should read:
"We’re actively looking for partner charities interested in experimenting with this visual storytelling format. So if you have a helpline, webchat, messaging service or even a face to face service, we could work together on whether an app could help people connect to those services"

**Comment by jermyk** [comment]
@HedgehogHolly @katjam 

The web page mentions the survey however the copy doesn't, which is correct?
![Screenshot_040219_102135_AM](https://user-images.githubusercontent.com/4446325/55391337-183e3800-5531-11e9-9c4a-a1b2379deca9.jpg)

**Comment by katquatermass** [comment]
Card refers to opening sentences only - so the website is correct


*Kat QuatermassService and Strategy Design*
Neontribe
Kat@neontribe.co.uk
0789 1487375

**Comment by jermyk** [comment]
@katquatermass :thumbsup:
