### ISSUE TITLE
Copy Edit: Supporters Page

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#113]
## Add sentence at beginning
This page, available in the landing page footer, allows organisations to thank their partners. 

## Acceptance Criteria
- [ ] The sentence "This page, available in the landing page footer, allows organisations to thank their partners." appears at the top of the Supporters page

**Comment by jermyk** [comment]
## Acceptance Criteria
- [x] the Supporters page, available in the landing page footer displays the sentence "This page"... and should appear at the top of the Supporters page,
![Screenshot_040219_101715_AM](https://user-images.githubusercontent.com/4446325/55391069-7cacc780-5530-11e9-85b3-382a667fb55a.jpg)
