### ISSUE TITLE
Update Privacy Policy

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#117]
## The Privacy Policy in the current version needs updating to current version
https://docs.google.com/document/d/1lNJ0PyLjlbkEa1G_AwlI-YhbB-tKTT5DriuImOROwSA/edit#heading=h.jb81tmh7f1j3

## Plan
- [x] See section - How is the information stored - 3 different privacy policies are referenced - the URL for each of these must be found and displayed in brackets in the copy
- [x] They copy in the app should be updated
- [x] The document linked here should be added to main page of this repo next to the content copy so it is easily available for the future
- [x] Editing should be turned off on that document

## Acceptance Criteria

- [ ] The links in the doc make sense. Some are not links. This AC is to check that the link copy and destination of all the purple links in the page make sense.
- [ ] Copy as per attached pdf (and un-editable copy doc which should be identical - but in case it gets re-opened - verify against pdf)

**Comment by katjam** [comment]
[Con-act-PrivacyCopyAt-v0.1.0-release.pdf](https://github.com/neontribe/contemplating-action/files/3030232/Con-act-PrivacyCopyAt-v0.1.0-release.pdf)

**Comment by jermyk** [comment]
@katjam @HedgehogHolly 
A few thoughts comments etc..

 ![Screenshot_040219_092138_AM](https://user-images.githubusercontent.com/4446325/55387105-b8439380-5528-11e9-9d22-3368af0a4ad9.jpg)
![Screenshot_040219_092334_AM](https://user-images.githubusercontent.com/4446325/55387247-fccf2f00-5528-11e9-9f5d-4c9ddbf970aa.jpg)
![Screenshot_040219_092549_AM](https://user-images.githubusercontent.com/4446325/55387400-4d468c80-5529-11e9-95b0-6adfaf8b492d.jpg)
![Screenshot_040219_092841_AM](https://user-images.githubusercontent.com/4446325/55387640-b3cbaa80-5529-11e9-8ba4-652988f285b9.jpg)
![Screenshot_040219_093305_AM](https://user-images.githubusercontent.com/4446325/55387969-5126de80-552a-11e9-91e0-d92d38ead08d.jpg)

**Comment by jermyk** [comment]
**Links**

@katjam @HedgehogHolly 
- [ ] Typeforms privacy policy & Google's privacy policy nav to the same place 
  https://www.typeform.com/help/gdpr-rights-for-respondents/
- [x]  CAST's privacy policy.  = https://www.castsoftware.com/privacy
- [x] ICO GDPR indvidual rights guide.  = https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/

**Comment by katjam** [comment]
@jermyk We thought the cookie one would be OK as it is. Well spotted though!

@HedgehogHolly can you please fix the Typeform and Google going to the same place - is probably a copy paste error.

**Comment by jermyk** [comment]
@katjam :thumbsup:
