### ISSUE TITLE
Tiny Typo in a Story Card

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#118]
From Testing: Show should read as Shows and making as taking

typo displaying on Part 4 of 4 of 1st Story
The final section of the story is about hope. It **show** that **making** a chance can be a positive choice. However it doesn’t suggest that the person’s life is now perfect. It is designed to encourage others to believe they could make a move to a more hopeful place too. It takes care not to sound out of reach.

## Plan
- [x] show to shows
- [x] making to taking

## Acceptance Criteria
- [x] Part 4 of 4 1st story reads: "It shows that taking a chance can be a positive choice. However it doesn’t suggest that the person’s life is now perfect. It is designed to encourage others to believe they could make a move to a more hopeful place too. It takes care not to sound out of reach."

**Comment by katjam** [comment]
@katquatermass I've added another typo fix here... but not sure if I am right.

Should it be "taking a chance" or "making a change"

Is currently "making a chance"

**Comment by katjam** [comment]
@katquatermass Did you get a chance to think about this?

Currently is:
![Screenshot_20190401_172140](https://user-images.githubusercontent.com/861172/55343169-796afa80-54a2-11e9-8d39-dfb28ea5b243.png)

**Comment by jermyk** [comment]
![Screenshot_040219_091644_AM](https://user-images.githubusercontent.com/4446325/55386754-0efc9d80-5528-11e9-86a7-877fe07de662.jpg)

**Comment by katquatermass** [comment]
I always meant "taking a chance" - as in taking a chance to get advice.
"making a change" is not the right phrase here it is too much for the small
step.  But I agree with Katja that it is not currently clear. Can we
replace with "asking for help or support"



*Kat QuatermassService and Strategy Design*
Neontribe
Kat@neontribe.co.uk
0789 1487375

**Comment by katjam** [comment]
@katquatermass Sorry for the confusion... I changed it to 'taking a chance' because it's what I thought you meant.

It was typo-d in originally as 'making a chance' - so I just wanted to double check that I'd make the right choice.

I think it is ok as it is now - but no problem to change if you still want to.

**Comment by katquatermass** [comment]
In that case I think I never made my mind up quite what worked so let's use
as is!
