### ISSUE TITLE
Decision and implementation on speech marks

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#119]
## See Karls image from testing on #51
If using quotation marks, should not have a space between final full stop and quotation mark.

## Plan
- [x] If quotation marks are a configuration thing - keep them - as other stories will always be "what someone said" and we can cope with it being odd for our project story
- [x] If quotation marks are NOT a configuration thing and are in the copy itself, remove them from the Project Story
- [ ] If keeping quotation marks, correct the end spacing

## Acceptance Criteria
. [ ] There should not be a space between the full stop and the quote mark

**Comment by katjam** [comment]
The quotes are in the css for all stories. Is easier to keep.

**Comment by katjam** [comment]
Closing as a won't fix. There is no space there - and I can't see it in the image either.

But @katquatermass We might want to have the subtitle things be a bit more consistent. In the project story - the one on slide 2 is uppercase start with a fullstop and the one on slide 4 is lowercase start with no fullstop. They also seem odd in quotes.

**Comment by katjam** [comment]
![Contemplating Action](https://user-images.githubusercontent.com/861172/55329622-f8ead080-5486-11e9-825a-ea7676c3c8e1.png)
