### ISSUE TITLE
Header height issue

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/contemplating-action#128]
## Description
Header height on pages other than front page seems to be messed up. It could be due to the change we made by removing the line height from the code earlier.

![Screenshot 2019-04-01 at 10 33 55](https://user-images.githubusercontent.com/41140803/55319489-e4014380-546c-11e9-9657-1d37bc085323.png)

## Plan
- [ ] Find out cause
- [ ] Fix issue in code

**Comment by katjam** [comment]
@HedgehogHolly We'll stick this in the backlog. The header font also seems to change sizes (is big on the homepage only).
