### ISSUE TITLE
Starter Story - Copy for the info (demo) version

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#13]
Create checklist of elements needing copy for configured version:

- [x] Title (was you matter)
- [x] Tagline (10 - 20 words)
- [x] Invitation (was show me the stories)
- [x] Encouragement to use related advice service and project contact details
- [x] Name and Tagline 
- [x] Encouragement to read story (3 words)
- [x] Story Structure Information in 4 parts (50 words a section goal)
- [x] 4 word intros to information sections
- [x] 50 - 75 word intro sections
- [x] check front page works as landing for survey and blog as well as app
- [ ] privacy notice or policy
- [x] supporters page

**Comment by katquatermass** [comment]
Story Structure google doc attached to #27 - Will also put it into the full copy doc that I'll do for the rest of this

**Comment by katquatermass** [comment]
https://docs.google.com/document/d/15jgy6AT6OFcZ98N4nHDvDxHB9nZpvuDfRXPdZuHQAzo/edit?usp=sharing

Latest version of content - and updated list of what is needed and missing.  Please do start getting this into the app when devs are ready in advance of those last two pieces - I think we're going to want to test with users/NT members who don't know the Haven initial project - to see if it makes sense - and I'd rather do that in situe than in the google doc.  Privacy and Supporters won't affect the main flow

**Comment by katquatermass** [comment]
Supporters page https://docs.google.com/document/d/1UO9ySPfZyOVEHFgrzQiFM5KxWDGA304GmG8GZ5H2dV4/edit?usp=sharing

**Comment by katquatermass** [comment]
First Draft Privacy Policy  (not the same as the PIA) - focused on the App that we are creating as Neontribe. New ones would exist/be written for any charity with whom we developed the app.
https://docs.google.com/document/d/1lNJ0PyLjlbkEa1G_AwlI-YhbB-tKTT5DriuImOROwSA/edit?usp=sharing    @neil-dabson @katjam   particularly interested in your comments

**Comment by katjam** [comment]
Moving Privacy copy out to #44

**Comment by jermyk** [comment]
![Screenshot_032719_014030_PM](https://user-images.githubusercontent.com/4446325/55080315-e3943180-5095-11e9-98ff-78948635405b.jpg)

Copy checked and commented on
