### ISSUE TITLE
Campaign Strategy 

### ISSUE THREAD

**Issue by rosejbon** [neontribe/contemplating-action#134]
## Important links
* Email copy: https://docs.google.com/document/d/1WmLkE9gR2qNzRPyw0rlxjKtIRn1_VfY2WaPzEIew1A4/edit?usp=sharing
* Who have we contacted spreadsheet: https://docs.google.com/spreadsheets/d/1IUNWx41BUqyoWxGTVvOUTsr6jrSFlT0Orc6yDzfy1g0/edit?usp=sharing

## Description
The aim of the **primary aim** of the Contemplating Action campaign is to get responses on the Contemplating Action survey. A **secondary aim** is to generate leads from decision makers in charities who would be interested in partnering with us on the project. 

Our **target audience** for the primary aim is staff or volunteers in non profit organisations who work closely with people seeking support. This may or may not include decision makers, so for our secondary aim we will need to target decision makers/influencers in third sector organisations.

## Key Tactics
I suggest that we utilise our personal contacts to get momentum moving on this project. Texting or emailing contacts we know who work in the sector asking them for 5 minutes of their time to read through our demo app and complete they survey. If people have contacted someone can they leave a note of who in this card.

To increase reach we should use Twitter with a regular campaign of tweets. I suggest we try a variation of promotional tactics and iterate until we find a couple that increase the reach. 

#### Reach
* Number of unique visitors
* Number of people clicking on the survey

#### Act
* Time of site
* Number of leads generated from survey 
* Number of retweets, likes and comments on related posts
* Emails to hello@contemplatingaction.org.uk
* 50 people complete the survey

#### Convert
* 10 leads from the survey undertake discussion on partnering with us on the Project

#### Engage
* 3 organisation partnered with us and there exists 3 contemplating actions projects for these organisation.

## Plan
- [x] Generate email template for Neontribers to use to contact personal and professional contacts
- [x] Email Ellie at CAST and cc Dan about putting contemplating action out there and provide copy with link
- [x] Generate content for tweets and schedule two weeks worth
- [x] Check in on the 12th April
- [ ] Access progress compared to campaign outcomes and outputs, and reassess if needed.

**Comment by katjam** [comment]
Done my initial list of email/ contact people.

**Comment by katquatermass** [comment]
Found the other people like Charity Digital https://digitalagenda.io/  - they send round an enews

**Comment by rosejbon** [comment]
- [ ] @roseb04 to go through the list again and see who we can talk to
- [ ] @roseb04 to speak to @katquatermass about Parkinsons UK
- [x] @roseb04 to speak to @harryharrold about Benjamin Foundation and Joe

**Comment by katjam** [comment]
Closing finished. Evidence is here.
