### ISSUE TITLE
Handover chat 24 April 11:30

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#140]
## Description
Handover from Kat to Katja and Rose

## Agenda
- [x] @katquatermass fill in plan agreed to date
- [x] @roseb04 fill in progress with charities

## Actions
- [ ] @katquatermass add time spent already in Kimai
- [x] @roseb04 to add her time
- [x] @katjam run a report on time spent to date for budget
- [x] @katjam make sure she knows where the budget doc is
- [x] @katjam update calendar with "Exploring Fears and Barriers" Workshops May, June collect stories, Dev in July (aiming for 3 sites)
- [ ] @katjam Take survey / info site down end of April #141 
- [x] Schedule chat with @katjam and @roseb04 for next catch-up in about 2 weeks.
- [x] @roseb04 to promote survey on Twitter
- [x] @roseb04 to sort out partners

## Timeline
- **now to 30th April:** survey
- **now to 17th May:** find partners
- **20th May to 14th June:** user research sessions
- **14th June to 28th June:** write content
- **July:** Dev time

## Project Info
- Want to work with 3 charities
- Fears and barriers workshop - half a day
- 1 chat with core worker to get fears and barriers or workshop depending on org
- Charities will source their own stories and rewrite, if they have blogs they can use them. We can work out if they work
- £1100 - covers staff time, costs for getting stories, refreshments for workshop, and social media promotions
- £150 per story for illustrations
- Maximum of 4 stories

**Comment by katjam** [comment]
@roseb04 Minutes here + add any actions. The we can make cards for all the actions (or do immediately if they are quick)

**Comment by katquatermass** [comment]
I have added budget link to wiki

**Comment by katquatermass** [comment]
I can't use Kimai - I get taught how on one day, then fail to do it the next then by the time I am trying again I can't reset my password.  Toby and Andy must collectively be fed up - but I cannot work out how to use the Neontribe systems effectively.
BUT if you are pulling off Kimai onto a CSV I can put my hours into the CSV....

**Comment by katjam** [comment]
@katquatermass Thank you! I'll export to csv and we can add yours as you suggest.

**Comment by rosejbon** [comment]
I can do the same! As I also haven't added my hours for a while ...

**Comment by katjam** [comment]
@roseb04 Prefer if you could do in the Kimai - since we might get out of sync otherwise.

**Comment by rosejbon** [comment]
@katjam I can do kimai, I shall do it now :)

I've also added info on this card with timelines and info on the project (mainly for my memory :D)

**Comment by katjam** [comment]
@roseb04 Ace! I think we could copy some of that info into the existing project info docs https://github.com/neontribe/contemplating-action/wiki

I try to keep them up to date and will do the timeline one as part of my calendar action here.

**Comment by rosejbon** [comment]
@katjam I agree! I need to work out how to use the wiki at some point!

Going to add time to kimai now

**Comment by katjam** [comment]
![Screenshot_20190501_160128](https://user-images.githubusercontent.com/861172/57023672-8bb79000-6c2a-11e9-966b-f177f92a746b.png)

**Comment by katjam** [comment]
Cant attach csv but I have it:


  |   |   |   |  
-- | -- | -- | -- | --
username | name | start_time | duration | description
katjam | Development tasks | 2019-03-19 13:22:00 | 5400 | Call to action feature
katjam | Development tasks | 2019-03-20 10:00:00 | 3600 | Call to action implementation
katjam | Development tasks | 2019-03-11 10:00:00 | 7200 | Code review & support
katjam | Development tasks | 2019-03-18 10:00:00 | 1800 | Code review
katjam | Development tasks | 2019-03-12 10:00:00 | 1800 | Code review
katjam | Development tasks | 2019-03-15 10:00:00 | 1800 | Code review
nick | Development tasks | 2019-03-21 13:30:00 | 5400 | Type form
katjam | Development tasks | 2019-03-14 10:00:00 | 1800 | Code review
nick | Development tasks | 2019-03-19 17:00:00 | 1800 | Code review
nick | Development tasks | 2019-03-05 09:00:00 | 7200 | Restyling work
nick | Development tasks | 2019-03-06 10:30:00 | 1800 | Code review and catchup calls
nick | Development tasks | 2019-03-07 10:15:00 | 3600 | Replace CSS classes
nick | Development tasks | 2019-03-08 08:00:00 | 7200 | Complete info version styling
  |   |   |   |  
katjam | Development tasks | 2019-03-25 10:00:00 | 1800 | Code review. Release.
nick | Development tasks | 2019-03-15 10:30:00 | 5400 | Code review and typeform dev
katjam | Development tasks | 2019-04-01 10:00:00 | 25200 | Prep release and last few copy changes. Some pairing with Holly.
katjam | Development tasks | 2019-03-29 10:00:00 | 7200 | Prep for heroku deploy and last few issue wrangle
katjam | Development tasks | 2019-01-17 12:06:00 | 1800 | Upgrade underlying packages
katjam | Development tasks | 2019-01-14 12:11:00 | 28800 | Create whitelabel site (was done in Sept 18 - but can put suitable date here within project funding scope)
Holly | Development tasks | 2019-01-28 11:26:00 | 7200 | NULL
nick | Development tasks | 2019-01-24 09:00:00 | 1800 | Build and code review
Holly | Development tasks | 2019-02-19 13:39:00 | 7200 | NULL
Holly | Development tasks | 2019-02-13 13:41:00 | 18000 | Illustrations
Holly | Development tasks | 2019-02-22 13:43:00 | 3600 | NULL
nick | Development tasks | 2019-03-04 17:00:00 | 1800 | CSS update
nick | Development tasks | 2019-03-01 18:00:00 | 1800 | CSS check and edits
Holly | Development tasks | 2019-03-04 12:03:00 | 10800 | Copy changes
katjam | Development tasks | 2019-03-05 10:00:00 | 3600 | Code review. Infrastructure. Bug fix.
katjam | Development tasks | 2019-03-06 10:00:00 | 5400 | Infrastructure and code review
Holly | Development tasks | 2019-03-06 12:58:00 | 14400 | adding pages and copy
Holly | Development tasks | 2019-03-05 14:45:00 | 10800 | NULL
Holly | Development tasks | 2019-03-07 15:48:00 | 19800 | NULL
katjam | Development tasks | 2019-03-07 10:00:00 | 7200 | Releases
katjam | Development tasks | 2019-03-08 10:00:00 | 1800 | Code review. Releases.
katjam | Development tasks | 2019-04-02 10:00:00 | 3600 | Prep for release
katjam | Development tasks | 2019-04-03 10:00:00 | 3600 | Release
katjam | Development tasks | 2019-04-04 10:00:00 | 1800 | Release and verify. Set timeout 15mins
nick | Development tasks | 2019-03-20 14:00:00 | 10800 | Development work
nick | Development tasks | 2019-04-01 12:00:00 | 5400 | Code review and discussion
nick | Development tasks | 2019-03-28 15:00:00 | 3600 | Code review and investigation
katjam | Development tasks | 2019-04-09 10:00:00 | 900 | Up timeout to 1 hour
katjam | Development tasks | 2019-04-16 10:00:00 | 3600 | Update readme for deploy process. Wrangle tickets.
katjam | Development tasks | 2019-04-17 10:00:00 | 1800 | Readme / release process & testing.
rose.neontribe | Development tasks | 2019-03-07 13:16:00 | 3600 | Set up Google Analytics
katjam | Project management & Testing  tasks | 2019-03-13 10:00:00 | 3600 | CAST call project update to Dan
nick | Project management & Testing  tasks | 2019-03-11 10:15:00 | 900 | Issue update
katjam | Project management & Testing  tasks | 2019-03-25 10:00:00 | 900 | Testing support
Jermalkl | Project management & Testing  tasks | 2019-03-28 10:41:00 | 28800 | Testing various chnages w/c 25th March
katjam | Project management & Testing  tasks | 2019-03-28 10:00:00 | 1800 | Progress call - prep for release
Jermalkl | Project management & Testing  tasks | 2019-03-29 14:57:00 | 3600 | Styling tests
Jermalkl | Project management & Testing  tasks | 2019-04-02 10:57:00 | 9000 | Copy testing
katjam | Project management & Testing  tasks | 2019-01-18 12:08:00 | 3600 | Set up timetracking and repo for PM
katjam | Project management & Testing  tasks | 2019-01-11 12:10:00 | 3600 | Initial repo clean and setup in prep for project. Set up meetings.
katjam | Project management & Testing  tasks | 2019-01-24 15:54:00 | 3600 | Meeting with Holly about what to customise & project generally
katjam | Project management & Testing  tasks | 2019-01-30 15:55:00 | 1800 | Review issue progress
katjam | Project management & Testing  tasks | 2019-02-07 10:00:00 | 10800 | Call & organising project
katjam | Project management & Testing  tasks | 2019-02-06 10:00:00 | 3600 | Prep work for project timelines
katjam | Project management & Testing  tasks | 2019-02-11 10:00:00 | 3600 | Demo/ Info instance design discussions & general management
katjam | Project management & Testing  tasks | 2019-02-25 10:00:00 | 1800 | Chasing tasks and check up project progress.
katjam | Project management & Testing  tasks | 2019-02-26 10:00:00 | 3600 | Progress catch-up meeting and plan this week
nick | Project management & Testing  tasks | 2019-02-25 09:30:00 | 1800 | Issue and design review
nick | Project management & Testing  tasks | 2019-02-26 11:00:00 | 2700 | Planning call
rose.neontribe | Project management & Testing  tasks | 2019-03-05 13:28:00 | 3600 | Copy for the stages of change
rose.neontribe | Project management & Testing  tasks | 2019-02-04 13:29:00 | 2700 | Catch up meeting
katjam | Project management & Testing  tasks | 2019-03-04 10:00:00 | 10800 | Get Holly started with dev. Code review and issue wrangling.
katjam | Project management & Testing  tasks | 2019-03-05 10:00:00 | 3600 | Issue wrangle. Code review.
rose.neontribe | Project management & Testing  tasks | 2019-02-27 13:30:00 | 3600 | PIA checklist creation
katjam | Project management & Testing  tasks | 2019-03-06 10:00:00 | 3600 | Issue wrangling
katjam | Project management & Testing  tasks | 2019-03-07 10:00:00 | 5400 | Planning
katjam | Project management & Testing  tasks | 2019-03-08 10:00:00 | 3600 | Issue wrangling. Chats. Plans.
nick | Project management & Testing  tasks | 2019-03-28 14:00:00 | 1800 | Update call
katjam | Project management & Testing  tasks | 2019-04-15 10:00:00 | 1800 | Action plan for survey
rose.neontribe | Project management & Testing  tasks | 2019-04-15 13:21:00 | 7200 | Contacting those who might be interesting in the project via email
rose.neontribe | Project management & Testing  tasks | 2019-04-15 13:22:00 | 900 | Meeting with Kat
rose.neontribe | Project management & Testing  tasks | 2019-04-23 13:23:00 | 1800 | Email those who expressed an interest in partnering
katjam | Project management & Testing  tasks | 2019-04-24 10:00:00 | 5400 | handover meeting Rose
nick | Project management & Testing  tasks | 2019-03-15 12:30:00 | 1800 | Catchup planning call
rose.neontribe | Planning | 2019-04-03 13:19:00 | 3600 | Draft campaign for survey and partner recruitment
rose.neontribe | Planning | 2019-04-08 13:20:00 | 3600 | Write up copy for social media campaign
rose.neontribe | Research | 2019-03-14 13:18:00 | 900 | Update survey and link

**Comment by katjam** [comment]
@roseb04 Added details to https://github.com/neontribe/contemplating-action/wiki/Timeline-and-rough-Project-outline.

Closing.
