### ISSUE TITLE
A list of assets we need from / for each charity site

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#142]
## Description
Come up with a list of stuff we need to build the sites

## Copy & images
- [ ] Stories - in format of 4 slides with some message text & images & teasers & information links
- [ ] Information pages - title and info blurb
- [ ] Home (landing) page copy & Front page image
- [ ] Privacy policy
- [ ] Supporters page (or similar) - to validate
- [ ] Call to action
- [ ] Contact
- [ ] Translations if appropriate (?)

## Design 
- [ ] Colours (specify how many and what for)
- [ ] Font
- [ ] Button design
- [ ] Link design
- [ ] Story & Info Card design
- [ ] more... tbc

**Comment by katjam** [comment]
@roseb04 this is a WIP off the top of my head. I can do more methodically when I get more time. I am guessing it will be helpful to create these as trello tasks to gather what we need on the boards.

**Comment by rosejbon** [comment]
Thanks Katja! Yeah I agree, good to keep them here for now though so we
have one central place we can disseminate info to partners from.

**Comment by katjam** [comment]
Find @HedgehogHolly initial work on this and link
