### ISSUE TITLE
Agenda 19th June

### ISSUE THREAD

**Issue by rosejbon** [neontribe/contemplating-action#146]
## Description
Meeting on the 19th June about CA

## Attendees
- Kat
- Harry
- Katja
- Rose

## Plan
- [ ] Contracts
- [ ] The handover of the final web app and clearing up what charities can and cannot do with the final site (i.e. could they hire a developer and make future edits to there site?)
- [ ] Monitoring/measuring success/insights from project
- [ ] Updating CAST

## Agenda
- [x] Review milestones
- [x] Update on charities & think about timeline a bit more Sept deadline.
- [x] Discuss domain & server hosting on individual charity basis
- [ ] Discuss github systems (labels and backlog)

**Comment by katjam** [comment]
## Description
Catch-up where we are with tasks

## Actions
- [x] @katjam to run up a report of time spent to date

**Comment by katjam** [comment]
Total:

Contemplating action at 2019-06-22 |  
-- | --
TOTAL (8hr days) | 22.2
Development | 9.6
Project Management & testing | 12.6




Kimai csv with Nick, Rose, Katja, Karl, Holly
[contemplatingactiontime20190622.tar.gz](https://github.com/neontribe/contemplating-action/files/3316877/contemplatingactiontime20190622.tar.gz)

Kat

Contemplating Action Time | Days | Days
-- | -- | --
  | Jan-March | April - June
Project Management | 2.75 | 0.5
Content Creation | 2 |  
User Research | 1.25 | 0.25
  | 6 | 0.75

**Comment by katjam** [comment]
@harryharrold I've dumped the kimai time and added @katquatermass into it. Total 22.2 days to now.
