### ISSUE TITLE
Analytics for each charity

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#147]
## Description
How do we need to approach metrics or each

**Comment by rosejbon** [comment]
What we are going to about it is:

- To talk to charities about what they do for analytics. 
- Have a chat with CAST 
- Look at deciding what Neontribe's position on it?

**Comment by katjam** [comment]
Interesting server package: https://goaccess.io which might be able to spit out rudimentary usage reports incrementally? No cookie needed since it grabs data from the access logs - not sure how it stands in terms of GDPR - can use in conjunction with GeoIP if we were interested also in rough Geo usage data.

**Comment by rosejbon** [comment]
I will research whether ico has any guidance on server access logs

**Comment by rosejbon** [comment]
@katjam, I believe this guidance from the ICO means that even if we use a server package to do analytics we would have to tell people and give them the option to opt in - 

> Functions usually performed by a cookie can be achieved by other means. This could include, for example, using certain characteristics to identify devices so that visits to a website can be analysed.

>PECR applies to any technology that stores or accesses information on the user’s device. This could include, for example, HTML5 local storage, Local Shared Objects and fingerprinting techniques.

Link to the full page it here: https://ico.org.uk/for-organisations/guide-to-pecr/guidance-on-the-use-of-cookies-and-similar-technologies/what-are-cookies-and-similar-technologies/

What do you think?

**Comment by rosejbon** [comment]
So @katjam, looking at it again with Rob, we may be able to use this, because we aren't doing this:

>The same rules also apply if you use any other type of technology to store or gain access to information on someone’s device.

So as long as the go access doesn't do that we should be fine. But I would need someone more techy to know whether it does or doesn't

**Comment by katjam** [comment]
I agree with @RpprRoger we wouldn't need to store anything on the users device. Nor would we attempt to identify them uniquely. I am not sure we'd get everything we need out of that sort of system - but we could try.

Some web hosts will already have available similar access log analysers via their control panels (I think). Google Analytics would give us more scope - like seeing which buttons are pressed and devices used (though I think goaccess can also do device info). Also not sure if we'd need to change the routing to make server requests and whether or not we could get time spent on pages accurately.

It seems like the simple solution is to get permission and use Google - since we already have that implemented and keep GoAccess or similar in mind.

@roseb04 Would it be best to close this and open one for looking into/ adding the cookie tracking widget?

**Comment by rosejbon** [comment]
Yeah I agree, lets stick with GA for now and keep GoAccess in mind for future builds. I will set up an issue for looking into adding cookie tracking widget.
