### ISSUE TITLE
Remove timeout

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#148]
## User Story
Our new charities probably won;t need the timeout function. If they do - will be easy to replace.

## Acceptance
- [ ] the app does not timeout

**Comment by katjam** [comment]
@roseb04 I'm leaving in the exit button - until we have evidence not wanted.

**Comment by Nikomus** [comment]
If we ever wanted to reinstate with the new timeout, we could disable by default by just setting the idleTimeLimit vars to -1
