### ISSUE TITLE
Catch-up 22 July

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#154]
## Description
What needs doing?

## Actions
- [ ] Everyone log time by Weds
- [x] Katja time report
- [x] Rose to card the accessibility issues
- [ ] Kat and Rose finishing this: https://github.com/neontribe/contemplating-action/issues/91

**Comment by katjam** [comment]
Assuming people have logged time to date:


  | Hours | Days
-- | -- | --
Total | 169.75 | 21
Dev | 79.75 | 10
PM / Plan / Research | 79 | 10
Illustration | 11 | 1

Plus @katquatermass time

**Comment by katjam** [comment]
@roseb04 Do you want time broken down any more than that? Do we need to make a code for each charity - or are we happy to lump into one slush - and believe that it will even out.

**Comment by katjam** [comment]
This pdf has kimai activity if we want more breakdown.

[contemplating-action-20190725.pdf](https://github.com/neontribe/contemplating-action/files/3435690/contemplating-action-20190725.pdf)

**Comment by rosejbon** [comment]
That's perfect thank you @katjam, I don't suppose you know how many days we got paid for?

**Comment by katjam** [comment]
Here is budget:
https://docs.google.com/spreadsheets/d/1s1kQOMbH9uKZoNxnmDwLptundjwDpBYO3UvCfgQ9xag/edit#gid=0

**Comment by katjam** [comment]
Moved on to #162
