### ISSUE TITLE
Cookie Banner

### ISSUE THREAD

**Issue by rosejbon** [neontribe/contemplating-action#183]
## Description

We need to give people the option to opt into having Google Analytics track them on the site - check re: cookie tracking widget

## Plan

- [ ] Think about how we do this
- [ ] What copy are we using?
- [ ]  Accessibility thought!
- [ ] Do we record things about the user between visits?
- [ ] Implement above if required
- [ ] Look into adding cookie tracking widget (https://www.cookiehub.com/)

##  Acceptance Criteria

- [ ] People opt-in not opt-out of cookies
- [ ] The cookie notice is clear and easy to find
- [ ] Opt in and opt out are given equal weight
- [ ] People can change their minds

**Comment by rosejbon** [comment]
@Nikomus is this copy ok for the cookie banner:

>We'd like to use Google Analytics cookies to collect and report information on how people use the site so we can improve it. Allowing us to use cookies does not allow us to identify you. For more information please see our 'Privacy Policy' page

**Comment by Nikomus** [comment]
@roseb04 I think it will be easier to have less text on the buttons, so can this be phrased more as a question? To be clear, the banner will show on each reload or revisit to the site. The three paths for it are:

Not pressed - Banner stays, no tracking
Press decline - Banner disappears for session, no tracking 
Press accept - Banner disappears for session, stats tracked

**Comment by rosejbon** [comment]
@Nikomus could we have 'off' 'on' for the buttons? Then we wouldn't have to phrase it as a question. Its a bit like how the ico do it

**Comment by Nikomus** [comment]
@roseb04 I think they use off and on because those are states, but we're asking the user for an action here. I can use those if you want but I think framing as a question with the buttons labelled with verbs is clearer.

**Comment by rosejbon** [comment]
@Nikomus ahhh ok, so how about:

> Can we use cookies to help improve this site? We'd like to use Google Analytics cookies to collect and report information on how people use the site. Allowing us to use cookies does not allow us to identify you. For more information please see our 'Privacy Policy' page

**Comment by rosejbon** [comment]
Too long?
