### ISSUE TITLE
Remove Exit Function

### ISSUE THREAD

**Issue by Nikomus** [neontribe/contemplating-action#216]
## Description
Remove Exit case from Update

## Plan
- [ ] Remove Exit case from Update

**Comment by katjam** [comment]
How did it get back in :(

**Comment by katjam** [comment]
You must have branched off for your cookie stuff before
https://github.com/neontribe/contemplating-action/commit/a300ae6c78c0b7e40075db4784bfe2c0d2acda7a#diff-6e79f775167692b85fb8131edb39ae4b

And stuck it back in on a conflict? Sorry I didn't see it in that last review.
