### ISSUE TITLE
Make information text aligned left

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/contemplating-action#226]
* [ ] Bite-size information is center-aligned, which can make it hard to read.
![image](https://user-images.githubusercontent.com/2150762/63448638-3ea83580-c436-11e9-9c65-5f76b18ed925.png)

**Comment by katjam** [comment]
This was a deliberate design decision by Steph that the information was more friendly to look at. It was known that we were making a trade-off - but was felt on balance that making the pages more pleasing to look at, they would be less intimidating.

Before we decide to do this, I'll have a look for any documented conversation. and @Nikomus and @falconx might remember more specifics.

**Comment by falconx** [comment]
I can't remember any conversations about it now but I would say as a rule of thumb to only center single lines of text/headlines. I would look to illustrations, colours and font styles to make pages feel more pleasing.

**Comment by HedgehogHolly** [comment]
Ah sorry @katjam I didn't see your message in time, I had already started working on it because I thought it was an easy fix that I could do. 

Rose and I had discussed that some of the info pages are difficult to read when the text is centered and then Harry pointed it out as well in his testing https://github.com/neontribe/ca-hospice-hope/issues/62 

We haven't used centered text on big paragraphs anywhere else in the designs, only short one or two lines of text. I also feel with white text on a coloured background plus the centered text, just adds a layer of difficulty when reading in my opinion. 

Generally the paragraphs on HH are a lot longer than Haven's information section so that is why I think it would be better suited to left aligned.

**Comment by katjam** [comment]
It's no problem at all. There were some conversations about it at the time
and the decision was made to stick with her design even though some of us
felt the content would be easier to consume if left aligned. I just wanted
to make sure we made the decision knowing that history - out of respect for
her design work.
