### ISSUE TITLE
Refreshing the page produces a 404

### ISSUE THREAD

**Issue by jermyk** [neontribe/contemplating-action#254]
User refreshed the page when on https://neontribe.github.io/stories# and witnessed a 404 error message.
![Screenshot_122019_042010_PM](https://user-images.githubusercontent.com/4446325/71268334-97d09900-2344-11ea-998e-55615c839a77.jpg)

**Comment by rosejbon** [comment]
We not worried about this, as we don't think it will appear in the final site, currently believe it is a odd github pages thing.
