### ISSUE TITLE
Design for info (demo) version

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#26]
## Description
Define a visual design for the #13 version

## Plan
- [ ] TBC

**Comment by katquatermass** [comment]
@HedgehogHolly  you might have enough info to start working on this... you have a sense of the feel of the project, you have the original app so you know what's configurable (or could set up a chat with Katja if you want to check through that) - illustrations will be dependent on my getting round to copy - but for design, I'm planning on keeping copy length reflective of current lengths so I think you could do look and feel? Maybe a couple of approaches if time?

**Comment by katjam** [comment]
![screenshot_20190211_102541](https://user-images.githubusercontent.com/861172/52557460-619ec080-2de7-11e9-8e9c-a0a53449d23b.png)

**Comment by HedgehogHolly** [comment]
First attempt at re-skin for demo version - [ContemplatingActions.pdf](https://github.com/neontribe/contemplating-action/files/2851838/ContemplatingActions.pdf)


**Colours**
Purple - #662483
Pink - #BD0076
Dark Blue - #30336d
Black - #3c3c3b
White - #F5F5F5
Light Grey - #E4E1E7

**Typography**
Header Info - Montserrat Alternates Semi Bold 17px #F5F5F5
Header Title -  Montserrat Alternates Semi Bold 40px #F5F5F5

H1 - Montserrat Alternates Bold 33px #3c3c3b
H2 - Montserrat Alternates Semi Bold 24px #3c3c3b and #30336d

Paragraph - Montserrat Alternates Medium 22px #3c3c3b

Footer Info -  Montserrat Alternates Semi Bold 17px #3c3c3b and #662483

**Icons**
[icons_svg.zip](https://github.com/neontribe/contemplating-action/files/2851834/icons_svg.zip)

**Images**
[images.zip](https://github.com/neontribe/contemplating-action/files/2855591/images.zip)


**Accessibility**
Blue - https://user-images.githubusercontent.com/41140803/52575420-15b74000-2e16-11e9-9871-aefc4b2ccd99.png
Purple - https://user-images.githubusercontent.com/41140803/52575422-164fd680-2e16-11e9-82e5-cec38e44cb84.png
Pink - https://user-images.githubusercontent.com/41140803/52575423-164fd680-2e16-11e9-9164-15c8fd648a20.png

**Comment by katjam** [comment]
@HedgehogHolly Amazing! Perfect and thorough. Thank you.

**Comment by katquatermass** [comment]
I think it's great.  I flip backwards and forwards between really loving Montserrat as a font and wondering about whether it actually looks balanced - especially in heavier weights. But am totally up for going with it for this if everyone else is cool with it.

Today and tomorrow I work on copy for the example version. Will start with the main story as I imagine illustrations will take most time.

**Comment by HedgehogHolly** [comment]
@katquatermass we can always go for a lighter version of Montserrat if you think the bold is too bold. Im also happy to create another version with a different typeface - if you would like to see that?

**Comment by HedgehogHolly** [comment]
I've added a zipped file with the images to the list @katjam

**Comment by katquatermass** [comment]
Worth a play with typeface if you have time I think... - its not that I think the bold is too bold, its that in bold it sometimes looks odd to me. But it might be good odd!

Once @Nikomus  has more free time (possibly Friday afternoon) I'd value his opinion so if we can have a couple for him to look at then, that'd be great

**Comment by HedgehogHolly** [comment]
Re-skin with typeface Poppins - [ContemplatingActions-Poppins.pdf](https://github.com/neontribe/contemplating-action/files/2856496/ContemplatingActions-Poppins.pdf)

**Typography**
Header Info - Poppins Semi Bold 17px #F5F5F5
Header Title -  Poppins Semi Bold 37px #F5F5F5

H1 - Poppins Semi Bold 37px #3c3c3b
H2 - Poppins Semi Bold 24px #3c3c3b and #30336d

Paragraph - Poppins Medium 21px #3c3c3b

Footer Info -  Poppins Medium 17px #3c3c3b and #662483

**Comment by HedgehogHolly** [comment]
@katquatermass did we make a choice on whether you want to go with Poppins or Montserrat?

**Comment by katquatermass** [comment]
Oh, no I didn't.
I think they are very similar in feel but Poppins doesn't have the slightly
stretched spacing of Montserrat and whilst I like that slightly stretched
effect as cool I think Poppins is a bit more balanced and will suit the
slightly formal tastes of a lot of the charity sector better and probably
be easier to read?
So if no-one else has opinions I'd stick with Poppins?

Kat

**Comment by HedgehogHolly** [comment]
We changed the colours so the latest update is:

### **Colours**
Purple - #662483
**Light Blue - #4575BA
Dark Blue - #1A1E64**
Black - #3c3c3b
White - #F5F5F5
Light Grey - #E4E1E7

and we've decided on Poppins as the typeface

### **Typography**
Header Info - Poppins Semi Bold 17px #F5F5F5
Header Title - Poppins Semi Bold 37px #F5F5F5

H1 - Poppins Semi Bold 37px #3c3c3b
H2 - Poppins Semi Bold 24px #3c3c3b and #30336d

Paragraph - Poppins Medium 21px #3c3c3b

Footer Info - Poppins Medium 17px #3c3c3b and #662483

[ContemplatingActions-blue.pdf](https://github.com/neontribe/contemplating-action/files/2893843/ContemplatingActions-blue.pdf)

**Comment by katjam** [comment]
@Nikomus Have a look when you get a chance. Would like to hear thoughts.

**Comment by Nikomus** [comment]
I think these are great! Very precise and ace to get colour accessibility right from the get-go.

I agree on font decision. Montserrat looks lovely, but is perhaps a bit too "opinionated" for a default/formal version.

I would maybe add another touch of the purple to elsewhere in the design to tie the buttons more into the otherwise blue colour-scheme (I know it's in the footer too), or it might be easier to sell as a default version without the purple at all? Either way, I think it's a nice clean design that charities will be able to see their own brand applied to 👍

**Comment by katquatermass** [comment]
I think keep purple - it shows they have more colour choices whereas if we
dropped it out it would look restricted - am sure @Holly Stringer
<holly@neontribe.co.uk> can find a way to make it more visible

**Comment by HedgehogHolly** [comment]
Now that you mention it, I can see what you mean Nick. The purple looks a little bit out of place but I definitely think it's worth keeping it. An all blue colour scheme might seem too corporate or remind people of the NHS.  I also agree with Kat it will be nice to show them a colour scheme with more colour choices.

I will have a play around and see if I can incorporate the purple more.

**Comment by HedgehogHolly** [comment]
I tried changing the info buttons to purple but Im not sure if they work - [ContemplatingActions-purpleandblue.pdf](https://github.com/neontribe/contemplating-action/files/2901228/ContemplatingActions-purpleandblue.pdf) 

Although this one looks better, using the dark blue for the icons instead of light blue - [ContemplatingActions-purpleandblue2.pdf](https://github.com/neontribe/contemplating-action/files/2901265/ContemplatingActions-purpleandblue2.pdf)

@Nikomus?

**Comment by katjam** [comment]
@HedgehogHolly It looks so great! I'm too excited.
