### ISSUE TITLE
Approach to charities

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#29]
## Description
Find charities to take part in workshops and creating app. Relies on #25 #10 

## Plan
- [ ] Kat is keeping a list of current prospects
- [ ] 2 meetings are lined up on 27th and 28th Feb to confirm a cancer charity and a mental health charity as partners (phone meeting on 27th rearranged to Monday 4th - organisation had a news story break and the worker who would've been on the call was on frontline chat)
- [ ] We have feelers out for 3rd and/or back up partners

**Comment by katjam** [comment]
@katquatermass @roseb04 @HedgehogHolly This is in the last milestone - but can be started now and perhaps should be to give enough time.

**Comment by katquatermass** [comment]
Agreed. Can be done with just the info from the project brief and a tiny bit of extra tweaking from me. Though I would *like* to wait til the blog post is ready if we can get that together by early next week

**Comment by katquatermass** [comment]
Rose is making a start by adapting the lists in tab two here  (these were broader, without close connections)
https://docs.google.com/spreadsheets/d/1m9WcMK-3N9W2e1UV1w4kBZiTFmqk0DBL_ekGW8oyju0/edit#gid=1126344893

**Comment by katquatermass** [comment]
Hope to have first phase of confirmations by Monday.

**Comment by katjam** [comment]
Closing. Putting plan followed in report.
