### ISSUE TITLE
Workshops with charities

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#30]
## Description
Workshops with charities to explore fears and barriers and plan stories

## Plan
- [ ] TBC - follow some of Haven's workshop plans that were effective?

**Comment by katquatermass** [comment]
Plans will depend on the selected charities - but the main focus will probably be a "fears and barriers" workshop - trying to identify 4 that are most crucial to address, to inform the selection of 4 stories.

**Comment by katjam** [comment]
Each project will have one.
