### ISSUE TITLE
Prep servers and deploy apps

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#34]
## Description
prepare Staging and Prod environs

## Plan
- [ ] Once charities identified - we'll need to get requirements. They will likely differ.
- [ ] TBC certainly to start we can use gh-pages for staging/ alphas

**Comment by katjam** [comment]
https://www.lcn.com/web-hosting/charity might be useful although these are not the charity's website - they are a supplementary app offered by a charity.

**Comment by rosejbon** [comment]
Rose will update seAp and Samaritan's contract that they will sort out the hosting and domain

**Comment by katjam** [comment]
Closing as a per brand issue.
