### ISSUE TITLE
Decide on an email forwarder (& site domain?) for the project

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#36]
## Description
Email and domain for the project needs setting up. We'll eventually need subdomains for the charities and the staging sites. No hosting needed yet - we'll consider that later.

## Plan
- [x] Purchase contemplatingaction.org.uk
- [x] Set up an email group for contemplatingaction@neontribe.co.uk going to Kat, Katja & Rose @neontribe.co.uk
- [x] Set up hello@contemplatingaction.org.uk to forward to contemplatingaction@neontribe.co.uk
- [ ] Add hello@contemplatingaction.org.uk to the site email (replacing ca@neontribe.co.uk)

**Comment by katquatermass** [comment]
@katjam - I hadn't integrated this into a milestone so we didn't raise this at the meeting - but we probably need it before deploy of the info app

**Comment by katjam** [comment]
conact@neontribe.co.uk ?

**Comment by katjam** [comment]
ca@neontribe.co.uk

**Comment by katjam** [comment]
cast@neontribe,co.uk (we use client name for many others)

**Comment by katquatermass** [comment]
conact - looks like a misspell of contact
ca@ - I think could work well even though because no caps initials for emails can be odd
cast@ I don't like for this - because its people outside the client who might use/see it most

Any other ideas?

contemplatingaction.org.uk is available as a domain 
The other possible I suppose is that as a domain, it can probably have an email so we do Hello@contemplatingaction.org.uk  and have that forward into a tribe address?

@andybarnes will no doubt be able to tell me if that's vastly more complicated than a @neontribe one

**Comment by katquatermass** [comment]
Assuming we intend to run standalone somewhere rather than at domain/neontribe.co.uk or anything?

**Comment by katjam** [comment]
I guess we might as well run it off contemplatingaction.org.uk as long @harryharrold thinks that's a good idea.

Alternatively contemplatingaction.neontribe.co .uk will also work.

For now running it only as a staging site at neontribe.github.io/contemplating-action

**Comment by katjam** [comment]
If we do the domain contemplatingaction.org.uk it will be fine to forward any of them to contemplatingaction@neontribe.co.uk and not have to come up with a shorter version.

**Comment by katjam** [comment]
@katquatermass Also in terms of domain - if we get contemplatingaction.org.uk we can put the initial demo sites up at charityname.contemplatingaction.org.uk which might work really well.

**Comment by katjam** [comment]
@katquatermass Does the plan look good? If so, I'll pass this on to @andybarnes

**Comment by katquatermass** [comment]
Works for me

**Comment by katjam** [comment]
@andybarnes Can you please do the 1st 3 things in the plan and then let @HedgehogHolly know so she can complete the last one.

No massive rush but would be good to get done by early next week if possible.

**Comment by ghost** [comment]
1 & 2 are trivial, 3 is not.

For 3 we either need an external mail provider and I need the authorisation to pay for an account, or we need to set up a mail server, and I'll need the authorisation to buy and pay ongoing for a server.

Do we have any decisions/information regarding what hosting we are going to use for the site, do we already have hostingfor the site? Do we have authorisation for an SSL (which we will also need to get the mail working if we are hosting the email)?

Who is going to own the hosting/email server account and domain, are they going to be owned by Neontribe, or are they going to be owned by a customer (and should, therefore, be separated onto their own customer-specific account)?

**Comment by ghost** [comment]
having checked our existing hosting accounts (LCN, UK2 and 123-reg) none of them offer wildcard email redirection, though they do offer individual mail box redirection.

**Comment by katjam** [comment]
![screenshot_20190307_133718](https://user-images.githubusercontent.com/861172/53960386-16be5300-40de-11e9-97db-55ceacf7c960.png)

**Comment by jermyk** [comment]
@katjam 

hello@ email address displaying in header menu
![Screenshot_032719_024412_PM](https://user-images.githubusercontent.com/4446325/55085562-c9ab1c80-509e-11e9-91aa-b8df1f7ed5c5.jpg)


Is there anything else required for the ticket in terms of testing?

Do we need to email the adress to make sure it's receiving mail?
