### ISSUE TITLE
Decide on info pages 

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#37]
## Description
We're rushing our first decisions through, without really testing - because the survey itself will be testing with users.... BUT I realised I don't want this to be just my first set of thoughts, would prefer input from others too

## Initial suggested buttons
- [ ] Bite size information
- [ ] Illustrations
- [ ] What is the survey?
- [ ] Can my organisation try this?
- [ ] What will taking part cost?
- [ ] Who is involved in this project?

**Comment by harryharrold** [comment]
Maybe a reference to illustrations, and how one might select them, as the second button, and roll choosing what to include into a single question about words?

**Comment by katquatermass** [comment]
@HedgehogHolly Can you now use these to do the buttons and icons on the information page for your designs - probably can add the blue colour in and take out actual photos at the same time?

**Comment by HedgehogHolly** [comment]
@katquatermass I can do that. Am I replacing the photos with the illustrations?

**Comment by katquatermass** [comment]
Front page yes pick one of yours. Elsewhere reduce no of stories and put in
illustrations for the two we keep I think rather than needing to find
enough for 6?

**Comment by HedgehogHolly** [comment]
Can we use the haven illustrations? or do I need to try and find some free to use ones?

**Comment by katquatermass** [comment]
Haven for the one haven story were using is fine I think
Kat

**Comment by HedgehogHolly** [comment]
Is this what you are looking for? - [ContemplatingActions-blue.pdf](https://github.com/neontribe/contemplating-action/files/2893827/ContemplatingActions-blue.pdf)

**Comment by katquatermass** [comment]
Yay!

**Comment by katquatermass** [comment]
These are now confirmed and integrated into main copy doc (order will change)
