### ISSUE TITLE
Catch-up meeting 7 March

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#39]
## Description
Catch-up where we are with tasks

## Agenda
- [x] Prep Milestone
- [x] Info version milestone
- [x] Update on charities & think about timeline a bit more
- [x] Discuss domain & server hosting
- [x] Discuss github systems (labels and backlog)

## Actions
- [ ] @katquatermass will write up research that does not include releasing test apps with Charities now
- [x] @katjam to run up a report of time spent to date
- [x] @harryharrold sign off for us to grab contemplatingaction.org.uk domain for the project pls?
- [ ] @katjam look into feasibility of embedding typeform/ custom url created #73)

**Comment by katquatermass** [comment]
Need to schedule a different time for this one - sorry - I'm in London with ARC I think

**Comment by katjam** [comment]
@katquatermass Want to do it 4th or 6th instead?

**Comment by katjam** [comment]
@katquatermass I guess if we convert the actions to issues, we then close this one?

**Comment by katjam** [comment]
Time spent on Contemplating Action @now:

5.6 days (Holly, Katja, Rose, Nick (1 Jan 2109 to 6 Mar 2019)

Though it also looks like @HedgehogHolly and @Nikomus need to log time for this week still.

**Comment by katquatermass** [comment]
Lets look next week  - and if easy by some kind of dev v engagement split

**Comment by katjam** [comment]
@katquatermass see time logged above... I reckon at least 1.5 days missing off that for Holly and Nick... mostly Holly

Do you need an issue for: ￼ @katquatermass will write up research that does not include releasing test apps with Charities now or is it part of one you already have?

Make one or ref one - and then close this catch-up issue.

**Comment by katquatermass** [comment]
Closing even though survey thing not yet done as it has its own card
