### ISSUE TITLE
Modifying the flow to include other support services

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#41]
## Urgent task for a Board Report
We need a version of the box flow diagram that includes a third icon in its bubble - a person walking in through a door - to include face to face services.  We also need a new line of copy in that box.

## Plan
- [x] New copy sentence put in a comment below by @katquatermass .
- [x] @HedgehogHolly to find icon and add it and comment to design

**Comment by katquatermass** [comment]
The individual leaves the app by one of the routes it offers to a support service

**Comment by HedgehogHolly** [comment]
@katquatermass below is the new pathway
![pathway](https://user-images.githubusercontent.com/41140803/53637787-001a8680-3c1c-11e9-89bf-aa5e946ba9f4.png)

**Comment by katquatermass** [comment]
Thank you! @roseb04 could you reply to my email and ping this over to them (I used it as an excuse to remind them of connection through you :)

**Comment by rosejbon** [comment]
@katquatermass yeah no probs, I've pinged them an email and reminded them they know (and hopefully like) me :D

**Comment by katquatermass** [comment]
@HedgehogHolly can you update the blog with this flow instead of the old one

**Comment by HedgehogHolly** [comment]
@katquatermass done! :+1:

**Comment by katjam** [comment]
@katquatermass @HedgehogHolly Can this be closed?

**Comment by HedgehogHolly** [comment]
I believe so
