### ISSUE TITLE
Agree Privacy Policy copy

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#44]
## Description
Agree an MVP privacy policy - was an item in #13 

## Plan
- [ ] Starting with https://docs.google.com/document/d/1lNJ0PyLjlbkEa1G_AwlI-YhbB-tKTT5DriuImOROwSA/edit?usp=sharing
- [ ] Once agreed we'll need to format and put in the site.

**Comment by katjam** [comment]
@katquatermass @neil-dabson I thought this warranted an issue of it's own. The google doc started by Kat is maybe too comprehensive? I guess it depends on the how far it needs to reach. The app itself will gather only google analytics data - though it also contains means of contacting us by phone or email and a link to Typeform survey.

**Comment by katquatermass** [comment]
Emailed Neil to check if he can review to appropriate timescales and if not then will ask Charlie in his stead

**Comment by katquatermass** [comment]
May revisit for future apps but currently have applied all Neil's suggested amends and are happy with this for current version
