### ISSUE TITLE
Add story one (Info story)

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#46]
## Description
Add the info story from #13 

## Plan
- [x] Add copy

## Acceptance Criteria
- [ ] Copy signed off in-situ by @katquatermass

**Comment by katjam** [comment]
@HedgehogHolly completed https://github.com/neontribe/contemplating-action/pull/42

**Comment by jermyk** [comment]
![Screenshot_032719_022700_PM](https://user-images.githubusercontent.com/4446325/55084017-67511c80-509c-11e9-8f5e-0fefe2881952.jpg)

**Comment by jermyk** [comment]
![Screenshot_032719_022740_PM](https://user-images.githubusercontent.com/4446325/55084069-7a63ec80-509c-11e9-8dd3-8ad3823c2d96.jpg)
![Screenshot_032719_022813_PM](https://user-images.githubusercontent.com/4446325/55084111-8d76bc80-509c-11e9-9e91-707bacd2f187.jpg)
![Screenshot_032719_022904_PM](https://user-images.githubusercontent.com/4446325/55084160-abdcb800-509c-11e9-9127-5f1fc61263bc.jpg)
![Screenshot_032719_022934_PM](https://user-images.githubusercontent.com/4446325/55084201-bdbe5b00-509c-11e9-87a9-d8c01c4e6d41.jpg)
![Screenshot_032719_023027_PM](https://user-images.githubusercontent.com/4446325/55084287-ddee1a00-509c-11e9-998c-311cfcc1f060.jpg)

**Comment by jermyk** [comment]
## Acceptance Criteria
- [x] Copy signed off in-situ by @katquatermass 

Comments re copy in https://github.com/neontribe/contemplating-action/issues/51
