### ISSUE TITLE
Add story two (Haven example)

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#47]
## Description
What needs doing?

## Plan
- [ ] Step one to achieve this.
- [ ] Step two to achieve this.

**Comment by jermyk** [comment]
**Haven's story**

![Screenshot_032719_014407_PM](https://user-images.githubusercontent.com/4446325/55080662-64532d80-5096-11e9-810a-09888ca397db.jpg)

**Comment by jermyk** [comment]
![Screenshot_032719_022230_PM](https://user-images.githubusercontent.com/4446325/55083638-c1051700-509b-11e9-93a3-2538a045f251.jpg)
![Screenshot_032719_022258_PM](https://user-images.githubusercontent.com/4446325/55083678-d1b58d00-509b-11e9-9f7e-b0eba6268243.jpg)
![Screenshot_032719_022331_PM](https://user-images.githubusercontent.com/4446325/55083737-e72ab700-509b-11e9-8f1b-b69e8e32dbe6.jpg)
![Screenshot_032719_022443_PM](https://user-images.githubusercontent.com/4446325/55083838-104b4780-509c-11e9-9e73-3a49b7695779.jpg)
