### ISSUE TITLE
Add info cards

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#48]
## Description
Copy from #13 into info cards

## Plan
- [x] Add copy

## Acceptance Criteria
- [ ] Get copy signed off by @katquatermass 
- [x] Test/ verify

**Comment by katjam** [comment]
@HedgehogHolly completed code https://github.com/neontribe/contemplating-action/pull/43

**Comment by jermyk** [comment]
![Screenshot_032719_014030_PM](https://user-images.githubusercontent.com/4446325/55080422-0de5ef00-5096-11e9-8e88-b3f8a08cd3df.jpg)

Copy checked on https://github.com/neontribe/contemplating-action/issues/51
All buttons fire
