### ISSUE TITLE
Icons for info cards & other elements

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#49]
## Description
Add new icons for the project

## Plan
- [x] Create an icomoon font (I think can upload custom to here)
- [x] Create/ edit icon.css to include them
- [x] Add icon spans to the info
- [x] Add info spans anywhere else we wnat icons
- [x] Look into where the icons are
- [ ] Store the raw files in the source somewhere ( carded for later #77 )

## Acceptance
- [x] Icons appear next to every Nav item on desktop
- [x] Icons appear next to every Nav item on mobile
- [x] Icons appear on every button (home page, info page and story page)
- [x] Icons appear at the top of every info page (text section)
- [x] Icons convey intended meaning

**Comment by jermyk** [comment]
@katjam 

AC #1 I need a steer as to where the icons should be appearing, so I can check that it is so?

**Comment by katjam** [comment]
@jermyk :+1: Fair point. I'll make a list.

**Comment by katjam** [comment]
@jermyk Done.

**Comment by jermyk** [comment]
@katjam 

Why does Take part in the survey host an icon and the others don't on this page?
![Screenshot_032919_022711_PM](https://user-images.githubusercontent.com/4446325/55239496-bd55c980-522e-11e9-8ab5-1f3aee63c81f.jpg)

**Comment by katjam** [comment]
@jermyk Good question - it's because it's the same as the Call button in Haven app. We do have icons for the individual info links though - so all but the "I'd like some other information" could have logos.

It just wasn't in the Haven design that way. Thoughts @Nikomus @HedgehogHolly ?
