### ISSUE TITLE
Set up Google analytics and update code

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#50]
## Description
Set up Google Analytics

Domain name: contemplatingaction.org.uk.

## Plan
- [x] Check if GA is reporting to Haven - or nowhere. UA000000
- [x] Create a property for the contemplating action site under the Neontribe Google account
- [x] Set up 'Raw Data' view
- [x] Set up a 'Test' view with bots excluded so we can use it to test any new Analytic configurations
- [x] Set up a 'Master' view with bots excluded and ignore Neontribe IP address
- [ ] Thoughts on how to filter by site - probably by subdomain for releases and staging/initial work as a lump ( we will decide this in future not for now)

**Comment by rosejbon** [comment]
I have set up Google Analytics for the site. We now just need to add the code to the site: 
```<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-30970110-10"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-30970110-10');
</script>
```

**Comment by katquatermass** [comment]
@roseb04 possibly help @jermyk with how to test this is live in Google Analytics Friday 29th

**Comment by jermyk** [comment]
@katjam
Tested using WASP.inspector
 
GA displaying on page
![Untitled_Clipping_032919_122440_PM](https://user-images.githubusercontent.com/4446325/55232483-9f339d80-521d-11e9-8948-7b5295c5a709.jpg)
