### ISSUE TITLE
Privacy page

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#52]
## Description
Add copy and markup to Privacy page

## Plan
- [x] Agree some MVP copy #44 
- [x] Add the copy

## Acceptance Criteria
- [x] Privacy policy can be viewed in the app
- [x] Copy signed off in situ by @katquatermass - we expect that this is a WIP and it has not been proofread. see #44

**Comment by jermyk** [comment]
@katquatermass 

Privacy page displays however it seems like the copy still needs sign off based on the comments from @neil-dabson in the document.
 
![Screenshot_032719_110923_AM](https://user-images.githubusercontent.com/4446325/55071523-cbfe7e00-5080-11e9-891a-6032a1a59aec.jpg)
![Screenshot_032719_111005_AM](https://user-images.githubusercontent.com/4446325/55071566-e0db1180-5080-11e9-8bcc-94c3bb4d0b7a.jpg)
![Screenshot_032719_111053_AM](https://user-images.githubusercontent.com/4446325/55071617-fcdeb300-5080-11e9-953f-c78ef68ac5cc.jpg)
![Screenshot_032719_111149_AM](https://user-images.githubusercontent.com/4446325/55071664-1e3f9f00-5081-11e9-99fc-d30f4190add2.jpg)
![Screenshot_032719_111404_AM](https://user-images.githubusercontent.com/4446325/55071779-7080c000-5081-11e9-88f4-de85d41555d8.jpg)

**Comment by katquatermass** [comment]
Yes agreed - the copy has been put in without a final pass over it - and includes some of my comments in brackets and possibly doesn't resolve all Neil's final suggestions.  I don't want to be the one who does this - security is not my specialism neither is the technical info thats requested in brackets in some places. @katjam what's the best way forward?

**Comment by katquatermass** [comment]
Need to incorporate a lot of the suggestions Neil has made into the document (which I thought I had done - we had a draft with the correct address in etc - am sure - but those are not here)

**Comment by katjam** [comment]
Final copy PDF 
[Con-act-PrivacyCopyAt-v0.1.0-release.pdf](https://github.com/neontribe/contemplating-action/files/3030389/Con-act-PrivacyCopyAt-v0.1.0-release.pdf)
