### ISSUE TITLE
Add Supporters page

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#53]
## Description
Add copy and markup to Supporters page

## Plan
- [ ] Add the copy & markup as per #13 

## Acceptance Criteria
- [x] Supporters info as per #13 can be reached
- [x] Copy signed off in situ by @katquatermass

**Comment by jermyk** [comment]
![Screenshot_032719_093654_AM](https://user-images.githubusercontent.com/4446325/55065505-dbc39580-5073-11e9-8e52-cebbd1f757ad.jpg)

![Screenshot_032719_093428_AM](https://user-images.githubusercontent.com/4446325/55065318-84bdc080-5073-11e9-838e-730090a0b148.jpg)


![Screenshot_032719_093758_AM](https://user-images.githubusercontent.com/4446325/55065834-7a4ff680-5074-11e9-8530-44dc3c32b60c.jpg)

**Comment by jermyk** [comment]
@katquatermass Copy is as per document.
