### ISSUE TITLE
Add info version styles to sass

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#54]
## Description
Style as per #26 

## Plan
- [x] Add styles to sass
- [x] Re-format structure if necessary
- [x] Think about how to streamline - we will repeat this for a few brands

## Acceptance Criteria
- [x] Visuallly similar to #26 
- [x] Pass accessibility lighthouse
- [x] Styles approved in situ by @katquatermass

**Comment by Nikomus** [comment]
I made some progress on this, there's a WIP branch here:
https://github.com/neontribe/contemplating-action/tree/0.1/54-info-version-sass

**Comment by katjam** [comment]
@Nikomus If this is stable - put up a PR. At a glance it looks like a concise bit of work to me and can go in in stages.

**Comment by jermyk** [comment]
@katquatermass @katjam @Nikomus @HedgehogHolly 

**Lighthouse Report screenshots**

![Screenshot_032919_121650_PM](https://user-images.githubusercontent.com/4446325/55232149-87a7e500-521c-11e9-837d-0b256b647054.jpg)
![Screenshot_032919_121728_PM](https://user-images.githubusercontent.com/4446325/55232178-9e4e3c00-521c-11e9-9fa4-e7464bf5eb53.jpg)
![Screenshot_032919_121757_PM](https://user-images.githubusercontent.com/4446325/55232206-af974880-521c-11e9-91aa-0ce69f3d6fbb.jpg)
![Screenshot_032919_121820_PM](https://user-images.githubusercontent.com/4446325/55232239-bd4cce00-521c-11e9-9427-e4db658662a1.jpg)
![Screenshot_032919_121842_PM](https://user-images.githubusercontent.com/4446325/55232253-ca69bd00-521c-11e9-914c-54d04a2134fe.jpg)

**Comment by Nikomus** [comment]
Accessibility 100 🙌
