### ISSUE TITLE
Optimise images

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#55]
## Description
Images are big and slow to load

## Plan
- [ ] Optimise as per Haven project plan (Alex made one)

## Acceptance Criteria
- [x] Images pass some kind of loading standard

**Comment by jermyk** [comment]
@katjam 

Need a steer with the AC for this one?

What devices are we using in terms of browser support if any?

**Comment by katjam** [comment]
@jermyk Maybe check with @katquatermass on browser support - but might save time if you can propose a list of what you think is reasonable. Not sure we've had any conversations.

You can use lighthouse as the loading standard and/ or google https://search.google.com/test/mobile-friendly

**Comment by katquatermass** [comment]
Yes I'd just assumed sticking to the same browsers as Haven. It will likely
be used on desktop more than Haven was intended for though, so perhaps we
should consider that - but I'm comfortable with the idea of "we've checked
and know which it works in" rather than "we must make it look right in all"

Kat

**Comment by katquatermass** [comment]
I'm sorry but I don't have time to find the haven browser list @jermyk - do you have access to the old files?

**Comment by jermyk** [comment]
Wave report
![Screenshot_032919_114021_AM](https://user-images.githubusercontent.com/4446325/55230333-6ee90080-5217-11e9-8c3a-58156785dff2.jpg)

**Comment by jermyk** [comment]
Interesting to see how the page renders here compared to the android issues on https://github.com/neontribe/contemplating-action/issues/106

 ![Screenshot_032919_114515_AM](https://user-images.githubusercontent.com/4446325/55230575-1e25d780-5218-11e9-904d-468c26723864.jpg)
![Screenshot_032919_114549_AM](https://user-images.githubusercontent.com/4446325/55230612-31d13e00-5218-11e9-83a1-bbd2818e7220.jpg)

**Comment by jermyk** [comment]
@katquatermass  @katjam @HedgehogHolly 

SUPPORTED BROWSER LIST FOR HAVEN - USED ON THE BETA

Do we want all of these for CA?

Devices: iPhone, iPad, Android Phone, Windows Phone and desktop
Browsers: Stock Android, Chrome, Safari, Edge, Firefox (latest stable release)

We test on Specific Combinations:

 - [ ] Android 4+ Phone - Stock browser
 - [ ] Android 4+ Phone - Chrome browser
 - [ ] Android 4+ Phone - Firefox Focus browser
 - [ ] ipad iOS7+ - Safari browser
 - [ ] iphone 5 iOS7+ - Safari browser 
 - [ ] iphone 6 iOS7+ - Safari browser 
 - [ ] iphone 7 iOS7+ - Safari browser 
 - [ ] Nokia Windows phone - IE 11 browser
 - [ ] Desktop - Chrome browser  - mouse
 - [ ] Desktop - Chrome browser  - touchscreen
 - [ ] Desktop - Firefox browser
 - [ ] Desktop - ie11
 - [ ] Desktop - edge
