### ISSUE TITLE
Front page content

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/contemplating-action#56]
## Description
Front page content needs to be changed 

## Plan
- [x] Agree copy in  #13 
- [x] Add copy 
- [x] Changed tagline
- [x] Changed button
- [x] Changed subheading
- [x] Changed paragraph
- [x] Changed greybar

## Acceptance Criteria
- [x]  Front page copy as per #13

**Comment by jermyk** [comment]
https://neontribe.github.io/contemplating-action/#

![Screenshot_032619_125911_PM](https://user-images.githubusercontent.com/4446325/54998831-f4c23d00-4fc6-11e9-94e2-5bdee42b3762.jpg)
![Screenshot_032619_125943_PM](https://user-images.githubusercontent.com/4446325/54998863-06a3e000-4fc7-11e9-83fc-de67ef64f8a9.jpg)
![Screenshot_032619_010012_PM](https://user-images.githubusercontent.com/4446325/54998886-17ecec80-4fc7-11e9-8a1c-aae6f6d9a271.jpg)
