### ISSUE TITLE
Content not showing in correct amounts

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#57]
## Description
Story 1 came out with 5 slides
One info link missing

## Acceptance Criteria
- [x] There is no default content visible in a single story
- [x] There is no default content visible in the info teaser page
- [x] There is no default content visible in the story teaser page
- [x] I can see all the info and stories from the #13 approved copy
- [x] Create an issue to make this configurable (or automatic) for next round of dev.

https://github.com/neontribe/contemplating-action/issues/108

**Comment by katjam** [comment]
@HedgehogHolly I'm going to investigate that rogue slide.

**Comment by jermyk** [comment]
@katjam AC#2 There is content and images from The Haven site in story 2 
https://neontribe.github.io/contemplating-action/#/stories/2

**Comment by jermyk** [comment]
.

**Comment by jermyk** [comment]
https://docs.google.com/document/d/15jgy6AT6OFcZ98N4nHDvDxHB9nZpvuDfRXPdZuHQAzo/edit?usp=sharing

@HedgehogHolly  - typo displaying on Part 4 of 4
The final section of the story is about hope. It **show** that making a chance can be a positive choice. However it doesn’t suggest that the person’s life is now perfect. It is designed to encourage others to believe they could make a move to a more hopeful place too. It takes care not to sound out of reach.

**Comment by katjam** [comment]
@katquatermass Check copy
