### ISSUE TITLE
Blog text link on front page

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/contemplating-action#61]
## Description

Kat's copy asks for a text link: read more about this project (goes to blog)  LINK. It needs to appear on front page under the paragraph.

Plan
- [x] update link to match blog post (at bottom of comments)

## Acceptance Criteria
- [x] The text description paragraph contains a link to the blog post.

**Comment by katjam** [comment]
@HedgehogHolly I'll wait for you to finish #62 and then show you how to put the link in.

**Comment by HedgehogHolly** [comment]
@katjam  I've done all the front page content other than that link now

**Comment by katjam** [comment]
The mark-up is a list html elements (with their content) so what you need to do to add an <a> element is stick it between the text elements.

e.g. if I wanted to turn "to encourage other women" into a link to the blog:

```
, p []
       [ text """In 2017, The Haven, Wolverhampton, Neontribe and women who had been 
       through domestic violence co-designed a web app
       """
       , a [ class "link link--plain", href "https://neontribe.co.uk/blog" ]
            [ text "to encourage other women " ]
       , text """in that situation to seek support and advice. We want to find out if the 
structure of that app could be used by different organisations to encourage people to use a helpline or web chat or text service. We believe that reassuring people that their fears and challenges are shared will help them take early steps on a journey of change. Explore the app and then take our survey to tell us what you think.
         """
        ]

```

**Comment by katjam** [comment]
The indentation is a bit odd because of the multiline text... but do you get the idea? Should format itself in your editor.

Without long text:

```
p[]
  [ text "Start the sentence with "
  , a [ class "link link--plain"][ text "the link text"]
  , text " in the middle of it."
  ]
```

**Comment by jermyk** [comment]
@katjam 

Link is not currently firing
![Screenshot_032519_052751_PM](https://user-images.githubusercontent.com/4446325/54940771-516c1c00-4f23-11e9-8527-a9a51e75cccd.jpg)
**BANG!!**
![Screenshot_032519_052716_PM](https://user-images.githubusercontent.com/4446325/54940733-3c8f8880-4f23-11e9-98d3-916ef5c1e59d.jpg)

**Comment by katquatermass** [comment]
I have put the blog live  at this address https://www.neontribe.co.uk/contemplating-action/

**Comment by jermyk** [comment]
## Acceptance Criteria
- [x] The text description paragraph contains a link to the blog post.
![Screenshot_040219_110545_AM](https://user-images.githubusercontent.com/4446325/55394464-43c42100-5537-11e9-8543-f1e6bc997cbb.jpg)

**Tested on desktop, Android and iPad devices.**
