### ISSUE TITLE
GDPR friendly email marketing platform

### ISSUE THREAD

**Issue by rosejbon** [neontribe/contemplating-action#63]
## Description
We need to find a GPDR compliant version of Mailchimp. Currently Mailchimps servers are in the US and therefore not GDPR complaint. Ideally we would like a similar email marketing platform for managing the emails of participants who provide their details on our survey.

## Plan
- [ ] @roseb04 to research email marketing platforms based in the UK/EU.
- [ ] View our options and discuss cost.

**Comment by rosejbon** [comment]
@katquatermass we have a couple of options, both of which have pretty good GDPR regs:

1) www.emailblasteruk.com - they are a UK based organisation with servers based in the UK. Quite pricey at £12.99 a month, but we could send up to 2000 emails if needed.

2) www.newzapp.co.uk - they are also a UK based organisation with servers in the UK. From what I can see it seems as if we can have a free account that allows us to send 50,000 emails. (I've set us up an account if we wish to use this)

**Comment by rosejbon** [comment]
If want a GDPR compliant survey form we can use Jotform, they have an EU safe form that stores all data in EU servers. They are very basic and there is a free account available (but is Jotform branded).

**Comment by katquatermass** [comment]
> If want a GDPR compliant survey form we can use Jotform, they have an EU safe form that stores all data in EU servers. They are very basic and there is a free account available (but is Jotform branded).

I'm comfortable with the enhanced functionality of typeform and our PIA which explores the limited data risk of using servers that are only under the EU privacy shield on a temporary basis, given the limited about of personal data in this project.

**Comment by katquatermass** [comment]
> @katquatermass we have a couple of options, both of which have pretty good GDPR regs:
> 
> 1. [www.emailblasteruk.com](http://www.emailblasteruk.com) - they are a UK based organisation with servers based in the UK. Quite pricey at £12.99 a month, but we could send up to 2000 emails if needed.
> 2. [www.newzapp.co.uk](http://www.newzapp.co.uk) - they are also a UK based organisation with servers in the UK. From what I can see it seems as if we can have a free account that allows us to send 50,000 emails. (I've set us up an account if we wish to use this)

Could you look for reviews of newzapp and see what it says about how good they are at getting past spam filters?   Alternately - we may actually decide not to send mass emails and only invididualised ones so can remove this need from the list.

**Comment by rosejbon** [comment]
@katquatermass I think we may need to go with Jotform as NewZapp are now quoting me a minimum contract of 1 year with prices start at £960 + VAT. So it is apparently not free.

**Comment by katquatermass** [comment]
Isn't that mail provider v. survey instead of like for like? or is jotform
offering mailer services as well?
I am erring towards we *might* just store the emails where they are (and
later in own cloud) and use individual mails (we could get a proton mail
account if NCVO's sign off suggests anything about its GDPR quality and we
don't want to send via gmail?)

**Comment by rosejbon** [comment]
@katquatermass Ignore me, not thinking before writing! Friday afternoon, sleepy brain. So it looks like neither UK based email marketing companies are free. And you are right, Jotform is completely different, it is a survey provider.

So I agree, I think we just store emails in Typeform and use individual emails. I also believe can make pretty emails using HTML so we might not need to go through a email marketing company if we were just using them for storage of emails and formatting.

**Comment by katquatermass** [comment]
Yes nothing to do with pretty - just bulk - they're better at dodging spam
filters - in general. IF we get strong survey response we can reconsider

Kat

**Comment by rosejbon** [comment]
Awesome, I shall close for now then
