### ISSUE TITLE
Interactive element styles

### ISSUE THREAD

**Issue by Nikomus** [neontribe/contemplating-action#69]
## Description
We need some extra colours for hover/focus/selected state of interactive things like links, to make them easier to use.

## Plan
- [x] Top nav links
- [x] Buttons
- [x] Footer text links
- [ ] Check for anything else

**Comment by HedgehogHolly** [comment]
@Nikomus 

I quite like a similar lime green to what Haven have for their focus state. Something like #C9EB85?
![screenshot 2019-03-07 at 15 31 08](https://user-images.githubusercontent.com/41140803/53969153-28105b00-40f0-11e9-882d-dde76dd6a44b.png)

Hover for purple buttons: #8B1ABC
![screenshot 2019-03-07 at 15 44 15](https://user-images.githubusercontent.com/41140803/53968985-e384bf80-40ef-11e9-911b-757fc58db224.png)

Hover for the text in the top nav and footer, could it simply be an underline effect?
![screenshot 2019-03-07 at 15 45 56](https://user-images.githubusercontent.com/41140803/53969130-1cbd2f80-40f0-11e9-85f0-79645263d33b.png)

Hover for the text link on stories page... as it already has an underline maybe just a change to the standard purple? #662483
![screenshot 2019-03-07 at 15 44 07](https://user-images.githubusercontent.com/41140803/53969101-0f07aa00-40f0-11e9-9a70-678371f76543.png)

**Comment by katjam** [comment]
@HedgehogHolly Sounds like a good plan to me. But sanity check by @Nikomus would be good too.

**Comment by Nikomus** [comment]
Sorry for not getting back to this sooner! We may want to improve the focus styles generally (at some point), I don't think many items have explicit focus styles.

For now make sure the outline is something that has good contrast with the background - lime green may be a little light.

**Comment by Nikomus** [comment]
This looks to have been resolved by https://github.com/neontribe/contemplating-action/pull/83

**Comment by jermyk** [comment]
@Nikomus 

The links aren't glaring obvious when they are in hover state, however the screenshot would suggest otherwise

Before
[Screenshot_032519_050309_PM](https://user-images.githubusercontent.com/4446325/54939208-e4a35280-4f1f-11e9-94ac-ee81376dde21.jpg)

During
On my desktop (windows 10) I can hardly see the colour change
![Untitled_Clipping_032519_050625_PM](https://user-images.githubusercontent.com/4446325/54939361-52e81500-4f20-11e9-8607-527bf410bd3a.jpg)
