### ISSUE TITLE
Update staging site in readme

### ISSUE THREAD

**Issue by Nikomus** [neontribe/contemplating-action#70]
## Description
The staging link in the readme is for an old site. It should be the staging URL we're using.

## Plan
- [x] update address to https://neontribe.github.io/contemplating-action/

**Comment by jermyk** [comment]
@katjam 

An observation - 
Currently the readme has a link that says **Demo** which leads to a staging site (which by rights is correct). However given that we also use DEMO as a site address sometimes COULD be confusing. 
![Screenshot_032519_045401_PM](https://user-images.githubusercontent.com/4446325/54938612-980b4780-4f1e-11e9-8328-26ea180c7c68.jpg)

Maybe change the readme to say staging so we differentiate and introduce some testing protocol?
