### ISSUE TITLE
Design and update favicon using new colours

### ISSUE THREAD

**Issue by Nikomus** [neontribe/contemplating-action#71]
## Description
We should replace the current favicon with something that uses the current brand colours, at some point

## Plan
- [ ] Design a new favicon
- [ ] Generate different sizes to replace all the current apple-icon, android-icon and favicon files in the src directory
- [ ] Replace in the code

![image](https://user-images.githubusercontent.com/32434620/54379652-bac97080-4681-11e9-82a7-c4c6f5be919b.png)

**Comment by HedgehogHolly** [comment]
@Nikomus is there a list of sizes we need somewhere? and are we just doing a gradient square in the brand colours?

**Comment by Nikomus** [comment]
@HedgehogHolly The gradient matched the header background that we used to have, so there's no need to recreate that particularly. Just something simple that uses the current colours that will help someone pick out the tab they were using. For sizes you can use a generator like this: https://www.favicon-generator.org/

**Comment by jermyk** [comment]
@HedgehogHolly  @katjam  fyi.

**Desktop**
![Screenshot_032519_024619_PM](https://user-images.githubusercontent.com/4446325/54928991-c122dc80-4f0c-11e9-8fd4-c4902a7e85b4.jpg)

**Android** 
![Screenshot_032519_024710_PM](https://user-images.githubusercontent.com/4446325/54929057-df88d800-4f0c-11e9-9f20-c746a0cd31d5.jpg)
