### ISSUE TITLE
Look into ( ? ) icon on Find Out More button

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/contemplating-action#78]
## Description
The ( ? ) icon on the Find Out More button seems slightly higher than it should be
## Plan
- [x] Check code
- [x] Fix issue

**Comment by jermyk** [comment]
![Screenshot_032519_023944_PM](https://user-images.githubusercontent.com/4446325/54928469-d5b2a500-4f0b-11e9-8ea1-3a1fcfc8102f.jpg)
