### ISSUE TITLE
Document the project plan/ outline 

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#8]
@katquatermass is working on this and will post in the wiki once it's out of early draft and has been assessed for suitability to be publicly available.

**Comment by katquatermass** [comment]
I think that we're ready - it may be amended and CAST still need to do final sign off, but I'd like to get it up here so we can change amend and crucially start adding dates....

Let me explore how to wiki!

**Comment by katjam** [comment]
I think this is covered by https://github.com/neontribe/contemplating-action/wiki
