### ISSUE TITLE
Rework Copy to reflect project better

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#80]
## Changes
Copy has an issue because the main explanatory paragraph lives below the fold on the landing page - as in main uses of the app we only want users to read that section if they're seeking info, it isn't part of their main journey. Also we're changing where we think we are with testing the app at present so some other sections are inaccurate

## Plan
- [x] rework info sections to duplicate that content.
- [x] rework that section to explain its intended function in a live app
- [x] rework info sections to reflect current project plan and introduce survey better
- [ ] update app with those reworkings
- [ ] test app with people who don't know the project

**Comment by katquatermass** [comment]
https://docs.google.com/document/d/15jgy6AT6OFcZ98N4nHDvDxHB9nZpvuDfRXPdZuHQAzo/edit?usp=sharing    New copy in bright pink @HedgehogHolly

**Comment by katjam** [comment]
Marking ready for release. This copy is tested elsewhere.
