### ISSUE TITLE
Work on improving the styling

### ISSUE THREAD

**Issue by HedgehogHolly** [neontribe/contemplating-action#82]
## Description
Check font sizing and styles, check colours.

## Plan
- [ ] Check font size
- [ ] Check font styles 
- [ ] Check colours
- [ ] Update code

**Comment by jermyk** [comment]
@HedgehogHolly 
Can you give me something to test this against please?

**Comment by katjam** [comment]
@HedgehogHolly We marked read for release as we assume you are generally happy with design. Was hard to test specifics.
