### ISSUE TITLE
Create survey icon

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#88]
## Description
Create a survey icon

## Plan
- [x] Create a survey icon
- [x] Add it to the font file
- [x] add it to the config for call to action
- [ ] consider uploading the icon set (used in ca) raw files to a dir (as per #77) as part of this task
- [x] Match the size and shape of the icons. e.g. the survery one is too small and thin.

**Comment by katjam** [comment]
@HedgehogHolly Can you please use this issue to make the icons a bit more simiar in weight and size? The find out more one is also a bit smaller and thinner.

![Screenshot_20190320_094257](https://user-images.githubusercontent.com/861172/54674497-73fdcf80-4af4-11e9-8a7d-b4749d1ba0bf.png)

**Comment by katjam** [comment]
Are we using all 3 of the £ symbol ones?

**Comment by katjam** [comment]
![Screenshot_20190320_094504](https://user-images.githubusercontent.com/861172/54674640-c5a65a00-4af4-11e9-8c8a-056bb32acf78.png)

**Comment by HedgehogHolly** [comment]
@katjam I think it would simply be easier to try and find fontawesome icons to replace the ones I made. That way they will definitely be the same size and weight? I'll look into wether there are appropriate icons.

**Comment by katjam** [comment]
Ok - whatever is easiest.

**Comment by jermyk** [comment]
## Acceptance Criteria
- [x] Places where Call to action is a survey link have the survey icon

From the header menu 
![Screenshot_032519_020523_PM](https://user-images.githubusercontent.com/4446325/54925833-08a66a00-4f07-11e9-82a4-3549d109c325.jpg)

From the homepage
![Screenshot_032519_020802_PM](https://user-images.githubusercontent.com/4446325/54926030-68047a00-4f07-11e9-863f-61e5e63c2601.jpg)

**Comment by jermyk** [comment]
@katjam 
![Screenshot_032519_020957_PM](https://user-images.githubusercontent.com/4446325/54926165-b1ed6000-4f07-11e9-88ac-22d3f75b09c7.jpg)
