### ISSUE TITLE
Can Neontribe receive grant funding for a project (eg without charging VAT)

### ISSUE THREAD

**Issue by katquatermass** [neontribe/contemplating-action#9]
This affects the project budget signficantly - plan to proceed in comments

**Comment by katquatermass** [comment]
Arrange a conversation between @neil-dabson and Dan at CAST so that Neil understands the process Dan has used with other commercial companies, and can then ask our accountants whether it will work for us? @harryharrold does that sounds like the right approach?

**Comment by katquatermass** [comment]
Also - for this first project which needs a budget now, accept that if VAT has to be charged, Neontribe will effectively discount the project in order to absorb VAT, a practice which would stop for any projects in 2019/20 onwards? @harryharrold seem wise?

**Comment by katjam** [comment]
@katquatermass closeable?

**Comment by katquatermass** [comment]
Neil still looking into it

**Comment by katquatermass** [comment]
Have emailed Neil a sample grant agreement from CAST (it didn't work last time)

**Comment by katjam** [comment]
@neil-dabson says:
the is it a grant or is it a contract issue is with the accountants, whom I have poked today as Harry asked.

**Comment by katquatermass** [comment]
We are not going to for this project. A number of other corporate organisations ARE finding themselves available to sign these grant agreements though, so we may need to consider revisiting with Accountants at some point.

This is a really detailed interpretation of the HMRC guidance by a charity accountant - note though that it applies to everyone - their status as a charity does NOT affect consideration 
[Sayer Vincent Guide] (http://www.sayervincent.co.uk/wp-content/uploads/2018/03/HMRC-grants-and-contracts-guidance.pdf)

We might consider tabulating how we feel the CAST grant passes or fails criteria and then working through that point by point with our accountants in future. Interestingly I believe that in this instance lack of a grants process would be a big push towards it being seen as services whilst receiving the money towards start of project would be a big push in the other direction!

**Comment by katquatermass** [comment]
Closing issue and leaving action with @harryharrold to ensure signing of something with Dan, and receiving money
