### ISSUE TITLE
Change the site meta in index.html

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#93]
## Description
Currently refers to 'Picture Stories and Information'

## Plan
- [ ] change the title, desc and image meta

**Comment by HedgehogHolly** [comment]
@katjam what should the description be? The title is Contemplating Action I am assuming.

**Comment by Nikomus** [comment]
@HedgehogHolly I guess we'll need a small amount of copy for this @katquatermass? The context for where this info is displayed is previews of links, eg if it's shared in Slack:

![image](https://user-images.githubusercontent.com/32434620/54428815-8eabff00-4716-11e9-9ba6-28d7317eeb20.png)

The image URL should be https://neontribe.github.io/contemplating-action/banner.png

**Comment by katquatermass** [comment]
I think
Contemplating Action
Exploring how visual storytelling can help people access support services

**Comment by jermyk** [comment]
![Screenshot_032519_020109_PM](https://user-images.githubusercontent.com/4446325/54925565-71d9ad80-4f06-11e9-8a35-8d05fb1f9609.jpg)
