### ISSUE TITLE
Consider time-out function

### ISSUE THREAD

**Issue by katjam** [neontribe/contemplating-action#98]
## User Story
As a Charity I want to be able to decide wheteher or not the app times out so that it makes sense for my users.

## Acceptance
- [ ] First step - for survey version hardcode to 15mins
- [ ] Info version of the app does not close unexpectedly
- [ ] Charities have a choice whether they want the timout function
- [ ] Charities that opt for the timeout can have it set a suitable time (per site instance)

**Comment by katjam** [comment]
@katquatermass suggests we set to 15mins for the info version.

![Screenshot_20190403_121950](https://user-images.githubusercontent.com/861172/55475003-a508f480-560a-11e9-9da1-ea08e86b68ee.png)

**Comment by katjam** [comment]
@roseb04 We've stripped this out for all the con act projects now. Can we close this issue?

**Comment by rosejbon** [comment]
We can indeed :D

**Comment by rosejbon** [comment]
Closing as per Katja's comment
